export const black = '#000000'
export const darkestGray = '#29292c'
export const darkGray = '#3d3e44'
export const darkPurple = '#282b36'
export const mediumGray = '#9b9aa1'
export const lightGray = '#DBDBDB'
export const lightWarmGray = '#f5f5f5'
export const offWhite = '#b7bdc5'
export const tan = '#fcf8f2'
export const thoughtbotRed = '#ed3e44'
export const transparent = 'rgba(0, 0, 0, 0)'
export const backDrop = 'rgba(0, 0, 0, 0.6)';
export const white = '#ffffff'
export const appPrimary = '#db3d32';
export const faintPrimary = "#d87d77"
export const _lightGray = "#bbb";
export const inputBg    = "rgb(250,250,250)";

export const baseText = darkGray
export const primary = appPrimary
export const darkestText = black;
export const darkText = darkestGray
export const sectionBackground = lightWarmGray
export const background = white
export const selected = thoughtbotRed
export const unselected = lightGray
export const shadowColor = black;
export const seperator = _lightGray;
export const toastBackground = black
